# ==============================================================================
# APP DEFINITIONS
# hyprctl clients -j | jq -r '.[] | "\(.class) -> \(.title)"'
# ==============================================================================
APP discord  vesktop                              vesktop
APP spotify  Spotify                              spotify
APP beeper   beepertexts                          beeper
APP todoist  chrome-app.todoist.com__app-Default  chromium --app=https://app.todoist.com/app --user-data-dir="/home/l4n1skyy/.config/todoist-app"
APP calendar chrome-calendar.google.com__-Default omarchy-launch-webapp https://calendar.google.com
APP obsidian obsidian                             obsidian
APP nvim     org.omarchy.nvim                     alacritty --class org.omarchy.nvim -e nvim
APP timr     timr-term                            alacritty --class timr-term -e timr
APP cbonsai  cbonsai-term                         alacritty --class cbonsai-term -e cbonsai -i -l
APP zen      zen-browser                          zen-browser

# ==============================================================================
# LAYOUT RULES
# GROUP <workspace> <alias>
# SPAWN <workspace> <alias>
# RATIO <workspace> <alias> <directions> <y_percent> <x_percent>
# FOCUS <workspace> <alias>
# ==============================================================================

# --- WORKSPACE 10: SOCIAL ---
GROUP 10 beeper discord spotify
FOCUS 10 beeper

# --- WORKSPACE 9: PRODUCTIVITY ---
GROUP 9 obsidian todoist calendar
FOCUS 9 obsidian

# --- WORKSPACE 2: BROWSING ---
SPAWN 2 zen

# --- WORKSPACE 1: THE DASHBOARD ---
RATIO 1 nvim        r       100%   80%
RATIO 1 timr        l,u     20%    20%
RATIO 1 cbonsai     l,d     80%    20%
FOCUS 1 nvim
